kind: Pod
apiVersion: v1
metadata:
  name: testflask
  labels:
    app: my-flask
spec:
  containers:
    - name: testflsk
      image: docker.jointree.co.kr/jointree/jointestflask
      ports:
        - containerPort: 80
          protocol: TCP
      imagePullPolicy: Always
      securityContext:
        privileged: true
  restartPolicy: Always
  imagePullSecrets:
    - name: docker-registry-login


